2023-03-22 17:44:34,132 ERROR Internal Server Error: /news/add/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'smtplib.SMTPDataError'>, SMTPDataError(554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1679496271-VirqZI1jm8c1-vjWG1Qsx'), <traceback object at 0x000001B4EDD8F980>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\auth\mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\edit.py", line 135, in form_valid
    self.object = form.save()
                  ^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\forms\models.py", line 549, in save
    self._save_m2m()
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\forms\models.py", line 530, in _save_m2m
    f.save_form_data(self.instance, cleaned_data[f.name])
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\related.py", line 1966, in save_form_data
    getattr(instance, self.attname).set(data)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1169, in set
    self.add(*new_objs, through_defaults=through_defaults)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1087, in add
    self._add_items(
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 1373, in _add_items
    signals.m2m_changed.send(
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
           ^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\news\signals.py", line 32, in notify
    msg.send()
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\mail\message.py", line 298, in send
    return self.get_connection(fail_silently).send_messages([self])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\mail\backends\smtp.py", line 131, in send_messages
    sent = self._send(message)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\mail\backends\smtp.py", line 149, in _send
    self.connection.sendmail(
  File "C:\Users\arzko\AppData\Local\Programs\Python\Python311\Lib\smtplib.py", line 908, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'5.7.1 Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1679496271-VirqZI1jm8c1-vjWG1Qsx')
2023-03-22 17:44:34,254 ERROR "POST /news/add/ HTTP/1.1" 500 158835 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-22 20:16:06,926 ERROR Internal Server Error: /news/20 D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '((news.article_image.url' from '((news.article_image.url'"), <traceback object at 0x000001A9B8B6D700>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '((news.article_image.url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '((news.article_image.url' from '((news.article_image.url'
2023-03-22 20:16:07,091 ERROR "GET /news/20 HTTP/1.1" 500 225598 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-22 20:17:32,157 ERROR Internal Server Error: /news/20 D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '*.jpg' from '*.jpg'"), <traceback object at 0x000001A9B8C9ED40>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '*.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '*.jpg' from '*.jpg'
2023-03-22 20:17:32,333 ERROR "GET /news/20 HTTP/1.1" 500 224772 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-22 20:21:25,846 ERROR Internal Server Error: /news/20 D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '(news.article_image.url.endswith(jpg)' from '(news.article_image.url.endswith(jpg)'"), <traceback object at 0x000001A9BA1E97C0>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '(news.article_image.url.endswith(jpg)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(news.article_image.url.endswith(jpg)' from '(news.article_image.url.endswith(jpg)'
2023-03-22 20:21:25,963 ERROR "GET /news/20 HTTP/1.1" 500 225333 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-26 16:09:18,380 ERROR Internal Server Error: /news/user/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'UserView' object has no attribute 'username'"), <traceback object at 0x0000020BDD71F940>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 225, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\news\views.py", line 116, in get_context_data
    context['cat_aut'] = Category.objects.filter(subscribers__in_user = self.username.user)
                                                                        ^^^^^^^^^^^^^
AttributeError: 'UserView' object has no attribute 'username'
2023-03-26 16:09:18,455 ERROR "GET /news/user/ HTTP/1.1" 500 89681 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-26 16:10:54,889 ERROR Internal Server Error: /news/user/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'NameError'>, NameError("name 'request' is not defined"), <traceback object at 0x000001EA02B8A480>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 225, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\news\views.py", line 116, in get_context_data
    context['cat_aut'] = Category.objects.filter(subscribers__in_user = request.user.username)
                                                                        ^^^^^^^
NameError: name 'request' is not defined
2023-03-26 16:10:54,916 ERROR "GET /news/user/ HTTP/1.1" 500 89553 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-26 16:11:18,792 ERROR Internal Server Error: /news/user/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'TypeError'>, TypeError("UserView.get_context_data() missing 1 required positional argument: 'request'"), <traceback object at 0x00000220F0F89040>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 225, in get
    context = self.get_context_data(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserView.get_context_data() missing 1 required positional argument: 'request'
2023-03-26 16:11:18,819 ERROR "GET /news/user/ HTTP/1.1" 500 85492 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-31 19:58:15,192 ERROR Internal Server Error: /index D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'bootstrap4' is not a registered tag library. Must be one of:\naccount\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nsocialaccount\nstatic\ntz"), <traceback object at 0x000002039D35E780>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'bootstrap4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'bootstrap4' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
custom_filters
flatpages
i18n
l10n
log
socialaccount
static
tz
2023-03-31 19:58:15,402 ERROR "GET /index HTTP/1.1" 500 178146 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-31 20:37:31,967 ERROR Internal Server Error: /accounts/profile D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'TypeError'>, TypeError("Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000001AC6DFE2150>>."), <traceback object at 0x000001AC6E1E5200>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\accounts\views.py", line 23, in dispatch
    if UsersAuth.objects.filter(user=self.request.user).exists():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\query.py", line 1421, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\query.py", line 1439, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\query.py", line 1446, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000001AC6DFE2150>>.
2023-03-31 20:37:32,080 ERROR "GET /accounts/profile HTTP/1.1" 500 134686 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-31 21:37:48,656 ERROR Internal Server Error: /contacts/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('flatpages/default.html'), <traceback object at 0x0000018AF964F180>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 161, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: flatpages/default.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\deprecation.py", line 138, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\flatpages\middleware.py", line 12, in process_response
    return flatpage(request, request.path_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\flatpages\views.py", line 45, in flatpage
    return render_flatpage(request, f)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\contrib\flatpages\views.py", line 70, in render_flatpage
    return HttpResponse(template.render({"flatpage": f}, request))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 64, in render
    reraise(exc, self.backend)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 85, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: flatpages/default.html
2023-03-31 21:37:48,750 ERROR "GET /contacts/ HTTP/1.1" 500 140110 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-03-31 21:54:33,246 ERROR Internal Server Error: /accounts/login/ D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("'socialaccount' is not a registered tag library. Must be one of:\naccount\nadmin_list\nadmin_modify\nadmin_urls\ncache\ncustom_filters\nflatpages\ni18n\nl10n\nlog\nstatic\ntz"), <traceback object at 0x0000020BEEFA2000>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1027, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'socialaccount'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1089, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 1029, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'socialaccount' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
custom_filters
flatpages
i18n
l10n
log
static
tz
2023-03-31 21:54:33,402 ERROR "GET /accounts/login/ HTTP/1.1" 500 194575 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-04-01 00:07:19,840 ERROR Internal Server Error: /post/4/edit D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('edit_post.html'), <traceback object at 0x00000261AD3DAC00>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: edit_post.html
2023-04-01 00:07:19,934 ERROR "GET /post/4/edit HTTP/1.1" 500 86976 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
2023-04-02 14:26:02,653 ERROR Internal Server Error: /post/2 D:\django_project\Message_board\venv1\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Could not parse the remainder: '{{responsesPost}}' from '{{responsesPost}}'"), <traceback object at 0x00000175AAD16F00>)
Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 179, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '{{responsesPost}}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 953, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 886, in __init__
    super().__init__(*args, **kwargs)
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 170, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\smartif.py", line 181, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\defaulttags.py", line 889, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\django_project\Message_board\venv1\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{responsesPost}}' from '{{responsesPost}}'
2023-04-02 14:26:02,839 ERROR "GET /post/2 HTTP/1.1" 500 229304 D:\django_project\Message_board\venv1\Lib\site-packages\django\core\servers\basehttp.py None
